server.port=8087
security.require-ssl=false
server.ssl.enabled=false

spring.datasource.url=${ERP_DB_URL:jdbc:mysql://erp-mysql:3306/sales_deep_dive_erp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${ERP_DB_USERNAME:root}
spring.datasource.password=${ERP_DB_PASSWORD:TMoswa@11}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true

application.jwt.secretKey=${ERP_JWT_SECRET:DailyDeepDiveV3DailyDeepDiveV3DailyDeepDiveV3DailyDeepDiveV3DailyDeepDiveV3}
application.jwt.tokenPrefix=Bearer
application.jwt.tokenExpirationAfterDays=10

frontend.appURL=${ERP_FRONTEND_URL:http://localhost:4300/}

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

